/**
 * 2D-1 — Refactor planner
 * One-time decision. Input: graph + summaries — never raw source.
 * Cost: ~$0.10–0.15 per call.
 * Saved to .wednesday/codebase/refactor/plan-<timestamp>.md
 */

'use strict';

const fs = require('fs');
const path = require('path');
const https = require('https');

/**
 * Build the prompt for refactor planning
 * Always graph + summaries — never raw source code
 */
function buildRefactorPrompt(goal, highRiskNodes, summaries, circularDeps) {
  const nodeList = highRiskNodes.slice(0, 10).map(n =>
    `${n.file} (risk:${n.riskScore}, dependents:${n.importedBy.length}): ${(summaries[n.file] || '').split('.')[0]}`
  ).join('\n');

  const circles = circularDeps.slice(0, 5).map(c => c.files.join(' → ')).join('\n');

  return `Refactor goal: "${goal}"

High-risk files:
${nodeList}

Circular dependencies:
${circles || 'none'}

Produce a refactor plan using GIT-OS commit format. Follow these rules:
- Max 5–6 files per PR
- Each step should be independently deployable
- Start with lowest-risk changes
- Format each step as: STEP N: [commit-type(scope): description] FILES: [list]
Return a numbered plan with max 8 steps.`;
}

/**
 * Call Sonnet for refactor planning
 */
async function callSonnet(prompt, apiKey) {
  return new Promise((resolve, reject) => {
    const body = JSON.stringify({
      model: 'anthropic/claude-sonnet-4-6',
      messages: [{ role: 'user', content: prompt }],
      max_tokens: 800,
      temperature: 0,
    });

    const options = {
      hostname: 'openrouter.ai',
      path: '/api/v1/chat/completions',
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${apiKey}`,
        'HTTP-Referer': 'https://github.com/wednesday-solutions/ai-agent-skills',
        'X-Title': 'Wednesday Skills Refactor Planner',
        'Content-Length': Buffer.byteLength(body),
      },
    };

    const req = https.request(options, res => {
      let data = '';
      res.on('data', c => { data += c; });
      res.on('end', () => {
        try {
          const json = JSON.parse(data);
          resolve(json.choices?.[0]?.message?.content?.trim() || null);
        } catch { resolve(null); }
      });
    });
    req.on('error', reject);
    req.setTimeout(60000, () => { req.destroy(); reject(new Error('timeout')); });
    req.write(body);
    req.end();
  });
}

/**
 * Generate and save a refactor plan
 */
async function planRefactor(goal, graph, summaries, legacyReport, refactorDir, apiKey) {
  const nodes = Object.values(graph.nodes);
  const highRiskNodes = nodes
    .filter(n => n.riskScore > 40)
    .sort((a, b) => b.riskScore - a.riskScore);

  const prompt = buildRefactorPrompt(goal, highRiskNodes, summaries, legacyReport?.circularDeps || []);

  let plan = null;
  if (apiKey) {
    try {
      plan = await callSonnet(prompt, apiKey);
    } catch {}
  }

  if (!plan) {
    plan = generateStructuralPlan(goal, highRiskNodes);
  }

  const timestamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19);
  const filename = `plan-${timestamp}.md`;
  const content = `# Refactor Plan — ${goal}
Generated: ${new Date().toISOString()}

${plan}

---
*Generated by wednesday-skills from graph analysis — not raw source code*
`;

  fs.mkdirSync(refactorDir, { recursive: true });
  const outPath = path.join(refactorDir, filename);
  fs.writeFileSync(outPath, content);
  return { plan, outPath };
}

function generateStructuralPlan(goal, highRiskNodes) {
  const steps = highRiskNodes.slice(0, 6).map((n, i) =>
    `STEP ${i + 1}: [refactor(${path.basename(n.file, path.extname(n.file))}): extracted from ${n.file}]\nFILES: ${n.file}\nRisk: ${n.riskScore} — ${n.importedBy.length} dependents`
  );

  return `## Plan: ${goal}

*API key not configured — structural plan only (no Sonnet reasoning)*

${steps.join('\n\n')}

Run with OPENROUTER_API_KEY set for AI-powered planning.`;
}

module.exports = { planRefactor };
