/**
 * Comment intelligence — module-wise comment aggregation, LLM enrichment, reverse PRD.
 *
 * Pipeline:
 *   1. collect()    — all comments per file, tagged + substantive untagged, grouped by dir
 *   2. enrich()     — batched Haiku calls (10 modules/call): purpose, techDebt, isBizFeature, ideas
 *   3. reversePrd() — single Haiku call: aggregate module purposes → project description
 *   4. emit()       → .wednesday/codebase/analysis/comments.json
 *
 * The module-level output feeds back into:
 *   - detectFeatureModules (isBizFeature boost)
 *   - MASTER.md (per-module comment context)
 *   - MAP_REPORT.md (feature module section)
 *   - SUMMARY.md (reverse PRD as opening paragraph)
 */

'use strict';

const fs = require('fs');
const path = require('path');
const { safeRead } = require('../core/parser');
const { callLLM } = require('../core/llm-client');

// ── Constants ─────────────────────────────────────────────────────────────────

const TAG_RE = /\b(TODO|FIXME|HACK|BUG|IDEA|NOTE|WARN(?:ING)?|DEPRECATED?|XXX|OPTIMIZE|PERF(?:ORMANCE)?|REVIEW|SMELL|TEMP(?:ORARY)?|KLUDGE)\b[:\s]?/i;

const SEVERITY = {
  FIXME: 'high', BUG: 'high', XXX: 'high',
  HACK: 'medium', KLUDGE: 'medium', SMELL: 'medium', TEMP: 'medium', TEMPORARY: 'medium',
  TODO: 'medium', OPTIMIZE: 'low', PERF: 'low', PERFORMANCE: 'low', REVIEW: 'low',
  IDEA: 'info', NOTE: 'info', WARN: 'info', WARNING: 'info', DEPRECATED: 'info', DEPRECATE: 'info',
};

// Noise patterns to discard even if they're long
const NOISE_RE = /eslint-disable|prettier-ignore|stylelint-disable|tslint:|copyright|license|generated by|auto-generated|do not edit|@flow|@ts-|@type |@param |@returns? |@throws |@see |@author |@version |@since /i;

const MIN_UNTAGGED_WORDS = 8;
const BATCH_SIZE = 10; // modules per Haiku call

// ── Comment extraction ────────────────────────────────────────────────────────

function extractComments(filePath, lang) {
  const src = safeRead(filePath);
  if (!src) return [];
  const comments = [];

  switch (lang) {
    case 'javascript': case 'typescript': case 'java': case 'csharp':
    case 'go': case 'kotlin': case 'swift': case 'c': case 'cpp': case 'php':
      extractCStyle(src, comments); break;
    case 'python': extractPython(src, comments); break;
    case 'ruby':   extractRuby(src, comments); break;
    case 'graphql': extractHash(src, comments); break;
    default: extractCStyle(src, comments);
  }

  return comments;
}

function extractCStyle(src, out) {
  let m;
  // Block comments
  const blockRe = /\/\*([\s\S]*?)\*\//g;
  while ((m = blockRe.exec(src)) !== null) {
    const startLine = lineAt(src, m.index);
    m[1].split('\n').forEach((l, i) => {
      const text = l.replace(/^\s*\*?\s?/, '').trim();
      if (text) out.push({ line: startLine + i, text });
    });
  }
  // Line comments
  const lineRe = /\/\/([^\n]*)/g;
  while ((m = lineRe.exec(src)) !== null) {
    const text = m[1].trim();
    if (text) out.push({ line: lineAt(src, m.index), text });
  }
}

function extractPython(src, out) {
  let m;
  const lineRe = /#([^\n]*)/g;
  while ((m = lineRe.exec(src)) !== null) {
    if (m.index === 0 && m[1].startsWith('!')) continue;
    const text = m[1].trim();
    if (text) out.push({ line: lineAt(src, m.index), text });
  }
  const docRe = /(?:"""([\s\S]*?)"""|'''([\s\S]*?)''')/g;
  while ((m = docRe.exec(src)) !== null) {
    const content = (m[1] || m[2]).trim();
    if (!content) continue;
    const startLine = lineAt(src, m.index);
    content.split('\n').forEach((l, i) => {
      const text = l.trim();
      if (text) out.push({ line: startLine + i, text });
    });
  }
}

function extractRuby(src, out) {
  let m;
  const lineRe = /#([^\n]*)/g;
  while ((m = lineRe.exec(src)) !== null) {
    if (m.index === 0 && m[1].startsWith('!')) continue;
    const text = m[1].trim();
    if (text) out.push({ line: lineAt(src, m.index), text });
  }
  const blockRe = /^=begin([\s\S]*?)^=end/gm;
  while ((m = blockRe.exec(src)) !== null) {
    const startLine = lineAt(src, m.index);
    m[1].split('\n').forEach((l, i) => {
      const text = l.trim();
      if (text) out.push({ line: startLine + i, text });
    });
  }
}

function extractHash(src, out) {
  let m;
  const lineRe = /#([^\n]*)/g;
  while ((m = lineRe.exec(src)) !== null) {
    const text = m[1].trim();
    if (text) out.push({ line: lineAt(src, m.index), text });
  }
}

// ── Categorisation ────────────────────────────────────────────────────────────

function categorise(comment, filePath) {
  const { line, text } = comment;
  if (NOISE_RE.test(text)) return null;

  const tagMatch = text.match(TAG_RE);
  if (tagMatch) {
    const rawTag = tagMatch[1].toUpperCase();
    const type = normaliseTag(rawTag);
    return {
      file: filePath,
      line,
      type,
      tagged: true,
      text: text.replace(TAG_RE, '').trim().slice(0, 200),
      severity: SEVERITY[rawTag] || 'info',
    };
  }

  // Keep untagged comments that are substantive (≥ MIN_UNTAGGED_WORDS words)
  const wordCount = text.split(/\s+/).filter(Boolean).length;
  if (wordCount >= MIN_UNTAGGED_WORDS) {
    return {
      file: filePath,
      line,
      type: 'NOTE',
      tagged: false,
      text: text.slice(0, 300),
      severity: 'info',
    };
  }

  return null;
}

function normaliseTag(t) {
  if (t === 'WARNING') return 'WARN';
  if (t === 'DEPRECATED' || t === 'DEPRECATE') return 'DEPRECATED';
  if (t === 'PERFORMANCE') return 'PERF';
  if (t === 'TEMPORARY') return 'TEMP';
  return t;
}

// ── Module-wise collection ────────────────────────────────────────────────────

/**
 * Group all comments by directory.
 * @returns {Map<string, { files: string[], tagged: Object[], untagged: Object[] }>}
 */
function collectByModule(nodes, rootDir) {
  const moduleMap = new Map();

  for (const [relFile, node] of Object.entries(nodes)) {
    if (node.error || node.lang === 'shell' || node.lang === 'config') continue;

    const dir = path.dirname(relFile);
    if (!moduleMap.has(dir)) {
      moduleMap.set(dir, { files: [], tagged: [], untagged: [] });
    }
    const mod = moduleMap.get(dir);
    mod.files.push(relFile);

    const absPath = path.resolve(rootDir, relFile);
    const rawComments = extractComments(absPath, node.lang);

    for (const raw of rawComments) {
      const item = categorise(raw, relFile);
      if (!item) continue;
      if (item.tagged) {
        mod.tagged.push(item);
      } else {
        mod.untagged.push(item);
      }
    }
  }

  return moduleMap;
}

// ── LLM enrichment ────────────────────────────────────────────────────────────

/**
 * Build a compact comment digest for a module (fits within token budget).
 */
function buildModuleDigest(dir, mod) {
  const lines = [`Module: ${dir}/  (${mod.files.length} files)`];

  // Up to 15 untagged comments (developer intent / explanations)
  const untaggedSample = mod.untagged.slice(0, 15);
  if (untaggedSample.length > 0) {
    lines.push('Comments:');
    untaggedSample.forEach(c => lines.push(`  ${c.file}:${c.line} — ${c.text}`));
  }

  // All tagged items (tech debt signals)
  if (mod.tagged.length > 0) {
    lines.push('Tagged:');
    mod.tagged.slice(0, 20).forEach(c => lines.push(`  [${c.type}] ${c.file}:${c.line} — ${c.text}`));
  }

  return lines.join('\n');
}

const MODULE_ENRICH_PROMPT = `You are analysing code comments grouped by module directory.

For each module below, respond with a JSON array. Each element must have exactly these fields:
- "dir": the module directory path (copy from input)
- "purpose": 1 sentence describing what this module does, inferred from its comments
- "techDebt": "high" | "medium" | "low" | "none"
- "isBizFeature": true if this looks like a business feature (auth, payments, users, orders...), false if infrastructure (utils, helpers, config, logging...)
- "ideas": array of max 3 concrete improvement suggestions, or []

Respond with ONLY the JSON array. No preamble. No markdown fences.

MODULES:
`;

/**
 * Enrich modules with Haiku in batches of BATCH_SIZE.
 * Returns Map<dir, { purpose, techDebt, isBizFeature, ideas }>
 */
async function enrichModules(moduleMap) {
  const dirs = [...moduleMap.keys()].filter(d => {
    const mod = moduleMap.get(d);
    return mod.tagged.length > 0 || mod.untagged.length > 0;
  });

  const enriched = new Map();

  // Process in batches
  for (let i = 0; i < dirs.length; i += BATCH_SIZE) {
    const batch = dirs.slice(i, i + BATCH_SIZE);
    const digest = batch
      .map(dir => buildModuleDigest(dir, moduleMap.get(dir)))
      .join('\n\n---\n\n');

    const raw = await callLLM({
      model: 'haiku',
      messages: [{ role: 'user', content: MODULE_ENRICH_PROMPT + digest }],
      maxTokens: 800,
      temperature: 0,
    });

    if (!raw) continue;

    try {
      // Strip any markdown fences if model adds them despite instruction
      const cleaned = raw.replace(/^```(?:json)?\n?/m, '').replace(/\n?```$/m, '').trim();
      const parsed = JSON.parse(cleaned);
      for (const item of parsed) {
        if (item.dir) enriched.set(item.dir, item);
      }
    } catch {
      // If JSON parse fails, skip this batch — structural data is best-effort
    }
  }

  return enriched;
}

// ── Reverse PRD ───────────────────────────────────────────────────────────────

const REVERSE_PRD_PROMPT = `You are reading module summaries extracted from code comments in a software project.

Based on the module descriptions below, write a concise reverse PRD (2–3 paragraphs) that describes:
1. What this product does and who uses it
2. The main user flows or business processes supported
3. The areas with the most technical debt or incomplete work

Module summaries:
`;

async function buildReversePrd(enrichedModules) {
  const bizModules = [...enrichedModules.values()].filter(m => m.isBizFeature && m.purpose);
  const infraModules = [...enrichedModules.values()].filter(m => !m.isBizFeature && m.purpose);

  if (bizModules.length === 0 && infraModules.length === 0) return null;

  const digest = [
    'Business features:',
    ...bizModules.slice(0, 15).map(m => `  ${m.dir}/: ${m.purpose}`),
    '',
    'Infrastructure:',
    ...infraModules.slice(0, 8).map(m => `  ${m.dir}/: ${m.purpose}`),
  ].join('\n');

  const result = await callLLM({
    model: 'haiku',
    messages: [{ role: 'user', content: REVERSE_PRD_PROMPT + digest }],
    maxTokens: 400,
    temperature: 0.2,
  });

  return result || null;
}

// ── Main entry point ──────────────────────────────────────────────────────────

/**
 * Run the full comment intelligence pipeline.
 *
 * @param {Object} nodes - dep-graph nodes
 * @param {string} rootDir - project root
 * @param {string} analysisDir - .wednesday/codebase/analysis/
 * @param {string|null} apiKey - optional API key
 * @returns {Object} full comment intel result
 */
async function analyseComments(nodes, rootDir, analysisDir, apiKey) {
  // Step 1: collect all comments, grouped by module
  const moduleMap = collectByModule(nodes, rootDir);

  // Flatten all items for the global tagged summary
  const allTagged = [];
  const allUntagged = [];
  for (const mod of moduleMap.values()) {
    allTagged.push(...mod.tagged);
    allUntagged.push(...mod.untagged);
  }

  // Build module summaries (without LLM first — structural data)
  const modules = [...moduleMap.entries()].map(([dir, mod]) => ({
    dir,
    fileCount: mod.files.length,
    files: mod.files,
    taggedCount: mod.tagged.length,
    untaggedCount: mod.untagged.length,
    tagsByType: mod.tagged.reduce((acc, i) => { acc[i.type] = (acc[i.type] || 0) + 1; return acc; }, {}),
    // LLM fields — filled in below if API key available
    purpose: null,
    techDebt: null,
    isBizFeature: null,
    ideas: [],
  }));

  let reversePrd = null;

  if (apiKey) {
    // Step 2: enrich each module with Haiku
    const enriched = await enrichModules(moduleMap);

    // Merge LLM data into module summaries
    for (const mod of modules) {
      const llm = enriched.get(mod.dir);
      if (llm) {
        mod.purpose = llm.purpose || null;
        mod.techDebt = llm.techDebt || null;
        mod.isBizFeature = llm.isBizFeature ?? null;
        mod.ideas = llm.ideas || [];
      }
    }

    // Step 3: reverse PRD from enriched modules
    reversePrd = await buildReversePrd(enriched);
  }

  // Global summary
  const byType = allTagged.reduce((acc, i) => { acc[i.type] = (acc[i.type] || 0) + 1; return acc; }, {});
  const bySeverity = allTagged.reduce((acc, i) => { acc[i.severity] = (acc[i.severity] || 0) + 1; return acc; }, {});

  // Top files by tagged comment density
  const byFile = allTagged.reduce((acc, i) => { acc[i.file] = (acc[i.file] || 0) + 1; return acc; }, {});
  const topFiles = Object.entries(byFile).sort((a, b) => b[1] - a[1]).slice(0, 10).map(([file, count]) => ({ file, count }));

  const result = {
    generatedAt: new Date().toISOString(),
    reversePrd,
    summary: {
      total: allTagged.length + allUntagged.length,
      taggedTotal: allTagged.length,
      untaggedTotal: allUntagged.length,
      byType,
      bySeverity,
      topFiles,
    },
    modules: modules.sort((a, b) => (b.taggedCount + b.untaggedCount) - (a.taggedCount + a.untaggedCount)),
    items: allTagged.sort((a, b) => {
      const order = { high: 0, medium: 1, low: 2, info: 3 };
      return (order[a.severity] ?? 9) - (order[b.severity] ?? 9);
    }),
  };

  fs.mkdirSync(analysisDir, { recursive: true });
  const outPath = path.join(analysisDir, 'comments.json');
  fs.writeFileSync(outPath, JSON.stringify(result, null, 2));

  return { ...result, outPath };
}

function lineAt(src, idx) {
  return src.slice(0, idx).split('\n').length;
}

module.exports = { analyseComments, extractComments, categorise, collectByModule };
