/**
 * Comment intelligence — module-wise comment aggregation + optional LLM enrichment.
 *
 * Collection pipeline (always runs, no LLM):
 *   1. collect()  — tagged + substantive untagged comments, grouped by directory
 *   2. emit()     → .wednesday/codebase/analysis/comments-raw.md  (pre-enrichment view)
 *   3. emit()     → .wednesday/codebase/analysis/comments.json    (structural data)
 *
 * Enrichment (purpose / techDebt / isBizFeature / ideas / reversePrd) — two paths:
 *   A. API key set  → CLI calls Haiku directly during map (fast, no agent needed)
 *   B. No API key   → LLM fields stay null; brownfield-enrich skill instructs the
 *                     running agent (Claude, Gemini, etc.) to enrich from comments-raw.md
 *
 * The enriched output feeds into:
 *   - detectFeatureModules (isBizFeature boost)
 *   - MASTER.md, MAP_REPORT.md, GUIDE.md, SUMMARY.md
 */

'use strict';

const fs = require('fs');
const path = require('path');
const { safeRead } = require('../core/parser');
const { callLLM } = require('../core/llm-client');

// ── Constants ─────────────────────────────────────────────────────────────────

const TAG_RE = /\b(TODO|FIXME|HACK|BUG|IDEA|NOTE|WARN(?:ING)?|DEPRECATED?|XXX|OPTIMIZE|PERF(?:ORMANCE)?|REVIEW|SMELL|TEMP(?:ORARY)?|KLUDGE|MARK)\b[:\s-]?/i;

const SEVERITY = {
  FIXME: 'high', BUG: 'high', XXX: 'high',
  HACK: 'medium', KLUDGE: 'medium', SMELL: 'medium', TEMP: 'medium', TEMPORARY: 'medium',
  TODO: 'medium', OPTIMIZE: 'low', PERF: 'low', PERFORMANCE: 'low', REVIEW: 'low',
  IDEA: 'info', NOTE: 'info', WARN: 'info', WARNING: 'info', DEPRECATED: 'info', DEPRECATE: 'info',
  MARK: 'info',
};

// Noise patterns to discard even if they're long
const NOISE_RE = /eslint-disable|prettier-ignore|stylelint-disable|tslint:|swiftlint:|swiftformat:|copyright|license|generated by|auto-generated|do not edit|@flow|@ts-|@type |@param |@returns? |@throws |@see |@author |@version |@since /i;

const MIN_UNTAGGED_WORDS = 8;
const BATCH_SIZE = 10; // modules per Haiku call

// ── Comment extraction ────────────────────────────────────────────────────────

function extractComments(filePath, lang) {
  const src = safeRead(filePath);
  if (!src) return [];
  const comments = [];

  switch (lang) {
    case 'javascript': case 'typescript': case 'java': case 'csharp':
    case 'go': case 'kotlin': case 'swift': case 'c': case 'cpp': case 'php':
      extractCStyle(src, comments); break;
    case 'python': extractPython(src, comments); break;
    case 'ruby':   extractRuby(src, comments); break;
    case 'graphql': extractHash(src, comments); break;
    default: extractCStyle(src, comments);
  }

  return comments;
}

function extractCStyle(src, out) {
  let m;
  // Block comments
  const blockRe = /\/\*([\s\S]*?)\*\//g;
  while ((m = blockRe.exec(src)) !== null) {
    const startLine = lineAt(src, m.index);
    m[1].split('\n').forEach((l, i) => {
      const text = l.replace(/^\s*\*?\s?/, '').trim();
      if (text) out.push({ line: startLine + i, text });
    });
  }
  // Line comments
  const lineRe = /\/\/([^\n]*)/g;
  while ((m = lineRe.exec(src)) !== null) {
    const text = m[1].trim();
    if (text) out.push({ line: lineAt(src, m.index), text });
  }
}

function extractPython(src, out) {
  let m;
  const lineRe = /#([^\n]*)/g;
  while ((m = lineRe.exec(src)) !== null) {
    if (m.index === 0 && m[1].startsWith('!')) continue;
    const text = m[1].trim();
    if (text) out.push({ line: lineAt(src, m.index), text });
  }
  const docRe = /(?:"""([\s\S]*?)"""|'''([\s\S]*?)''')/g;
  while ((m = docRe.exec(src)) !== null) {
    const content = (m[1] || m[2]).trim();
    if (!content) continue;
    const startLine = lineAt(src, m.index);
    content.split('\n').forEach((l, i) => {
      const text = l.trim();
      if (text) out.push({ line: startLine + i, text });
    });
  }
}

function extractRuby(src, out) {
  let m;
  const lineRe = /#([^\n]*)/g;
  while ((m = lineRe.exec(src)) !== null) {
    if (m.index === 0 && m[1].startsWith('!')) continue;
    const text = m[1].trim();
    if (text) out.push({ line: lineAt(src, m.index), text });
  }
  const blockRe = /^=begin([\s\S]*?)^=end/gm;
  while ((m = blockRe.exec(src)) !== null) {
    const startLine = lineAt(src, m.index);
    m[1].split('\n').forEach((l, i) => {
      const text = l.trim();
      if (text) out.push({ line: startLine + i, text });
    });
  }
}

function extractHash(src, out) {
  let m;
  const lineRe = /#([^\n]*)/g;
  while ((m = lineRe.exec(src)) !== null) {
    const text = m[1].trim();
    if (text) out.push({ line: lineAt(src, m.index), text });
  }
}

// ── Categorisation ────────────────────────────────────────────────────────────

function categorise(comment, filePath) {
  const { line, text } = comment;
  if (NOISE_RE.test(text)) return null;

  const tagMatch = text.match(TAG_RE);
  if (tagMatch) {
    const rawTag = tagMatch[1].toUpperCase();
    const type = normaliseTag(rawTag);
    return {
      file: filePath,
      line,
      type,
      tagged: true,
      text: text.replace(TAG_RE, '').trim().slice(0, 200),
      severity: SEVERITY[rawTag] || 'info',
    };
  }

  // Keep untagged comments that are substantive (≥ MIN_UNTAGGED_WORDS words)
  const wordCount = text.split(/\s+/).filter(Boolean).length;
  if (wordCount >= MIN_UNTAGGED_WORDS) {
    return {
      file: filePath,
      line,
      type: 'NOTE',
      tagged: false,
      text: text.slice(0, 300),
      severity: 'info',
    };
  }

  return null;
}

function normaliseTag(t) {
  if (t === 'WARNING') return 'WARN';
  if (t === 'DEPRECATED' || t === 'DEPRECATE') return 'DEPRECATED';
  if (t === 'PERFORMANCE') return 'PERF';
  if (t === 'TEMPORARY') return 'TEMP';
  return t;
}

// ── Module-wise collection ────────────────────────────────────────────────────

/**
 * Group all comments by directory.
 * @returns {Map<string, { files: string[], tagged: Object[], untagged: Object[] }>}
 */
function collectByModule(nodes, rootDir) {
  const moduleMap = new Map();

  for (const [relFile, node] of Object.entries(nodes)) {
    if (node.error || node.lang === 'shell' || node.lang === 'config') continue;

    const dir = path.dirname(relFile);
    if (!moduleMap.has(dir)) {
      moduleMap.set(dir, { files: [], tagged: [], untagged: [] });
    }
    const mod = moduleMap.get(dir);
    mod.files.push(relFile);

    const absPath = path.resolve(rootDir, relFile);
    const rawComments = extractComments(absPath, node.lang);

    for (const raw of rawComments) {
      const item = categorise(raw, relFile);
      if (!item) continue;
      if (item.tagged) {
        mod.tagged.push(item);
      } else {
        mod.untagged.push(item);
      }
    }
  }

  return moduleMap;
}

// ── LLM enrichment ────────────────────────────────────────────────────────────
//
// Two enrichment paths — same output shape, different executor:
//   1. API key available → CLI calls Haiku directly (fast, cheap, no agent needed)
//   2. No API key        → brownfield-enrich skill instructs the running agent to
//                          read comments-raw.md and write enriched fields back
//
// Both paths produce the same comments.json schema. The skill path sets enrichedAt
// after writing so consumers can tell which path ran.

/**
 * Build a compact comment digest for a module (fits within token budget).
 */
/**
 * Build a digest for a module — uses comments if present, otherwise structural file info.
 */
function buildModuleDigest(dir, mod, nodes = {}) {
  const lines = [`Module: ${dir}/  (${mod.files.length} files)`];

  const fileInfos = mod.files.slice(0, 10).map(f => {
    const n = nodes[f];
    if (!n) return `  ${path.basename(f)}`;
    const role = n.role || '';
    const sigs = n.meta?.signatures ? ` | sigs: ${n.meta.signatures.slice(0, 200)}` : '';
    const exp  = n.exports.slice(0, 5).join(', ');
    return `  ${path.basename(f)} [${role}] exports: ${exp || 'none'}${sigs}`;
  });
  lines.push('Files:\n' + fileInfos.join('\n'));

  if (mod.untagged.length > 0) {
    lines.push('Dev comments:');
    mod.untagged.slice(0, 10).forEach(c => lines.push(`  ${path.basename(c.file)}:${c.line} — ${c.text}`));
  }

  if (mod.tagged.length > 0) {
    lines.push('Tagged comments:');
    mod.tagged.slice(0, 15).forEach(c => lines.push(`  [${c.type}] ${path.basename(c.file)}:${c.line} — ${c.text}`));
  }

  return lines.join('\n');
}

const MODULE_ENRICH_PROMPT = `You are analysing source code modules. For each module, infer its purpose from file names, exported symbols, roles, and any developer comments present. Even when there are no comments, file names like "AuthViewController", "PaymentService", or "UserRepository" clearly indicate intent — use them.

For each module below, respond with a JSON array. Each element must have exactly these fields:
- "dir": the module directory path (copy exactly from input)
- "purpose": 1 sentence describing what this module does. Use file names and exports as primary signal. Never return null — always infer something from the file names.
- "techDebt": "high" | "medium" | "low" | "none" — base on tagged comments (FIXME/HACK/TODO) if present, otherwise "none"
- "isBizFeature": true if this is a business feature (auth, payments, users, orders, home, onboarding, search, chat, media...), false if infrastructure (utils, helpers, config, logging, extensions, base classes...)
- "ideas": array of max 3 concrete improvement suggestions from TODO/FIXME comments, or []

Respond with ONLY the JSON array. No preamble. No markdown fences.

MODULES:
`;

// ── Pattern-based fallback enrichment ─────────────────────────────────────────

const BIZ_PATTERNS = /auth|login|logout|signin|signup|register|password|token|otp|biometric|user|profile|account|avatar|settings|preference|home|dashboard|feed|payment|billing|checkout|cart|order|invoice|subscription|stripe|purchase|notif|alert|push|onboard|walkthrough|splash|search|filter|discover|chat|message|inbox|conversation|camera|photo|video|image|gallery|media|upload|map|location|geo|analytics|tracking/i;

const INFRA_PATTERNS = /util|helper|extension|base|common|shared|core|config|logging|logger|network|http|client|api|service|manager|router|coordinator|constant|enum|protocol|interface|error|handler|validator|formatter|parser|serializ|deserializ|mapper|test|mock|stub|fake|fixture|spec/i;

/**
 * Infer enrichment fields from structure and comments without LLM.
 * Used as the initial pass (always runs) and as fallback when LLM fails.
 */
function inferFromPatterns(dir, mod) {
  // ── isBizFeature ────────────────────────────────────────────────────────────
  const allNames = [dir, ...mod.files.map(f => path.basename(f, path.extname(f)))].join(' ');
  const isBizFeature = BIZ_PATTERNS.test(allNames) && !INFRA_PATTERNS.test(dir);

  // ── purpose from dir/file names ────────────────────────────────────────────
  const dirBase = path.basename(dir);
  let purpose = null;
  if (dirBase && dirBase !== '.') {
    // Convert camelCase/PascalCase/kebab-case to words
    const words = dirBase
      .replace(/([a-z])([A-Z])/g, '$1 $2')
      .replace(/[-_]/g, ' ')
      .toLowerCase();
    purpose = `${isBizFeature ? 'Business' : 'Infrastructure'} module for ${words}.`;
  } else if (mod.files.length > 0) {
    const firstName = path.basename(mod.files[0], path.extname(mod.files[0]));
    purpose = `Module containing ${mod.files.length} file${mod.files.length > 1 ? 's' : ''} (${firstName} and others).`;
  }

  // ── techDebt from tagged comments ──────────────────────────────────────────
  const highCount = mod.tagged.filter(c => c.severity === 'high').length;
  const medCount  = mod.tagged.filter(c => c.severity === 'medium').length;
  let techDebt = 'none';
  if (highCount >= 3 || (highCount >= 1 && medCount >= 2)) techDebt = 'high';
  else if (highCount >= 1 || medCount >= 3) techDebt = 'medium';
  else if (medCount >= 1 || mod.tagged.length > 0) techDebt = 'low';

  // ── ideas from TODO/FIXME text ─────────────────────────────────────────────
  const ideas = mod.tagged
    .filter(c => ['TODO', 'FIXME', 'HACK', 'BUG', 'IDEA'].includes(c.type) && c.text.length > 10)
    .slice(0, 3)
    .map(c => c.text.slice(0, 120));

  return { purpose, techDebt, isBizFeature, ideas };
}

/**
 * Enrich modules via direct Haiku calls (API key path).
 * Returns Map<dir, { purpose, techDebt, isBizFeature, ideas }>
 */
async function enrichModules(moduleMap, nodes = {}) {
  // Include all directories — file names alone are enough signal for purpose + isBizFeature.
  // Skip only dirs with a single file that has no exports and no comments (truly empty modules).
  const dirs = [...moduleMap.keys()].filter(d => {
    const mod = moduleMap.get(d);
    if (mod.files.length === 0) return false;
    if (mod.files.length === 1 && mod.tagged.length === 0 && mod.untagged.length === 0) {
      const n = nodes[mod.files[0]];
      if (!n || (n.exports.length === 0 && !n.isEntryPoint)) return false;
    }
    return true;
  });

  // Seed enriched with pattern-based values so every dir has something even if LLM fails
  const enriched = new Map();
  for (const dir of dirs) {
    enriched.set(dir, inferFromPatterns(dir, moduleMap.get(dir)));
  }

  for (let i = 0; i < dirs.length; i += BATCH_SIZE) {
    const batch = dirs.slice(i, i + BATCH_SIZE);
    const digest = batch
      .map(dir => buildModuleDigest(dir, moduleMap.get(dir), nodes))
      .join('\n\n---\n\n');

    // Baseline = tokens the summarizer would spend calling Haiku per file WITHOUT enrichment.
    // Each enriched module dir's files would each need a ~150-token Haiku call.
    // Enrichment prevents all of those calls by providing purpose from comments instead.
    const batchFileCount = batch.reduce((s, dir) => s + (moduleMap.get(dir)?.files.length || 0), 0);
    const baselineTokens = batchFileCount * 150;

    const raw = await callLLM({
      model: 'haiku',
      messages: [{ role: 'user', content: MODULE_ENRICH_PROMPT + digest }],
      maxTokens: 2000,  // 10 modules × ~150 tokens/module + JSON overhead, with headroom
      temperature: 0,
      operation: 'comment-intel',
      baselineTokens,
    });

    if (!raw) continue;

    try {
      const cleaned = raw.replace(/^```(?:json)?\n?/m, '').replace(/\n?```$/m, '').trim();
      const parsed = JSON.parse(cleaned);
      for (const item of parsed) {
        if (!item.dir) continue;
        // Normalize dir: strip trailing slash the LLM may have copied from the prompt
        const normalizedDir = item.dir.replace(/\/$/, '');
        // Merge LLM result over the pattern fallback — LLM wins on non-null fields
        const existing = enriched.get(normalizedDir) || {};
        enriched.set(normalizedDir, {
          ...existing,
          purpose:      item.purpose      || existing.purpose,
          techDebt:     item.techDebt     || existing.techDebt,
          isBizFeature: item.isBizFeature ?? existing.isBizFeature,
          ideas:        (item.ideas && item.ideas.length > 0) ? item.ideas : existing.ideas,
        });
      }
    } catch {
      // JSON parse failed — pattern fallback already seeded, nothing lost
    }
  }

  return enriched;
}

// ── Reverse PRD ───────────────────────────────────────────────────────────────

const REVERSE_PRD_PROMPT = `You are reading module summaries extracted from code comments in a software project.

Based on the module descriptions below, write a concise reverse PRD (2–3 paragraphs) that describes:
1. What this product does and who uses it
2. The main user flows or business processes supported
3. The areas with the most technical debt or incomplete work

Module summaries:
`;

async function buildReversePrd(enrichedModules) {
  const bizModules  = [...enrichedModules.values()].filter(m => m.isBizFeature && m.purpose);
  const infraModules = [...enrichedModules.values()].filter(m => !m.isBizFeature && m.purpose);

  if (bizModules.length === 0 && infraModules.length === 0) return null;

  const digest = [
    'Business features:',
    ...bizModules.slice(0, 15).map(m => `  ${m.dir}/: ${m.purpose}`),
    '',
    'Infrastructure:',
    ...infraModules.slice(0, 8).map(m => `  ${m.dir}/: ${m.purpose}`),
  ].join('\n');

  const result = await callLLM({
    model: 'haiku',
    messages: [{ role: 'user', content: REVERSE_PRD_PROMPT + digest }],
    maxTokens: 400,
    temperature: 0.2,
    operation: 'comment-intel',
  });

  return result || null;
}

// ── Raw preprocessing report ─────────────────────────────────────────────────

/**
 * Write comments-raw.md — the full collection result before any LLM call.
 * Always generated. Shows exactly what was found per module so you can verify
 * collection is working during live testing or debugging.
 */
function writeRawReport(moduleMap, analysisDir) {
  const allTagged   = [...moduleMap.values()].flatMap(m => m.tagged);
  const allUntagged = [...moduleMap.values()].flatMap(m => m.untagged);
  const totalFiles  = new Set([...allTagged, ...allUntagged].map(i => i.file)).size;

  // Global tag counts
  const byType = allTagged.reduce((acc, i) => { acc[i.type] = (acc[i.type] || 0) + 1; return acc; }, {});
  const tagRows = Object.entries(byType).sort((a, b) => b[1] - a[1])
    .map(([t, n]) => `| \`${t}\` | ${n} |`).join('\n');

  const lines = [
    '# Comment Collection — Raw Preprocessing',
    '',
    `> Generated: ${new Date().toISOString()}`,
    `> Files with comments: ${totalFiles} | Modules: ${moduleMap.size} | Tagged: ${allTagged.length} | Substantive untagged: ${allUntagged.length}`,
    `> LLM enrichment: **not run yet** — this file is the pre-LLM view`,
    '',
    '## Global tag breakdown',
    '',
    '| Tag | Count |',
    '|-----|-------|',
    tagRows || '| — | 0 |',
    '',
    '---',
    '',
  ];

  // Per-module sections — sorted by total comment count descending
  const sortedModules = [...moduleMap.entries()]
    .filter(([, m]) => m.tagged.length + m.untagged.length > 0)
    .sort((a, b) => (b[1].tagged.length + b[1].untagged.length) - (a[1].tagged.length + a[1].untagged.length));

  for (const [dir, mod] of sortedModules) {
    lines.push(`## \`${dir}/\` — ${mod.files.length} file${mod.files.length !== 1 ? 's' : ''}, ${mod.tagged.length} tagged, ${mod.untagged.length} substantive`);
    lines.push('');

    // Files in module
    lines.push(`**Files:** ${mod.files.map(f => `\`${f}\``).join(', ')}`);
    lines.push('');

    // Tagged comments
    if (mod.tagged.length > 0) {
      const tagSummary = Object.entries(
        mod.tagged.reduce((acc, i) => { acc[i.type] = (acc[i.type] || 0) + 1; return acc; }, {})
      ).map(([t, n]) => `${n}× ${t}`).join(', ');

      lines.push(`**Tagged (${mod.tagged.length}):** ${tagSummary}`);
      lines.push('');
      lines.push('| Severity | Tag | File | Line | Comment |');
      lines.push('|----------|-----|------|------|---------|');
      for (const item of mod.tagged) {
        const sev = item.severity === 'high' ? '🔴' : item.severity === 'medium' ? '🟡' : item.severity === 'low' ? '🔵' : '⚪';
        const text = item.text.replace(/\|/g, '\\|').slice(0, 100);
        lines.push(`| ${sev} | \`${item.type}\` | \`${item.file}\` | ${item.line} | ${text} |`);
      }
      lines.push('');
    }

    // Substantive untagged comments
    if (mod.untagged.length > 0) {
      lines.push(`**Substantive untagged (${mod.untagged.length}):** developer explanations, architecture notes, etc.`);
      lines.push('');
      // Show up to 10 per module — these are the richest signal for purpose extraction
      const sample = mod.untagged.slice(0, 10);
      for (const item of sample) {
        lines.push(`- \`${item.file}\`:${item.line} — ${item.text.replace(/\|/g, '\\|').slice(0, 150)}`);
      }
      if (mod.untagged.length > 10) {
        lines.push(`- *...and ${mod.untagged.length - 10} more*`);
      }
      lines.push('');
    }

    lines.push('---');
    lines.push('');
  }

  if (sortedModules.length === 0) {
    lines.push('> No comments found. Either the codebase has no comments, or all comments were filtered as noise.');
    lines.push('');
  }

  lines.push('*Raw collection — no LLM involved. Run `wednesday-skills map` with an API key to enrich with purpose, tech debt, and ideas.*');

  fs.mkdirSync(analysisDir, { recursive: true });
  const outPath = path.join(analysisDir, 'comments-raw.md');
  fs.writeFileSync(outPath, lines.join('\n'));
  return outPath;
}

// ── Main entry point ──────────────────────────────────────────────────────────

/**
 * Run the comment intelligence pipeline.
 *
 * Always writes:
 *   - comments-raw.md  — full pre-enrichment view (no LLM, always generated)
 *   - comments.json    — structural data + LLM fields if enrichment ran
 *
 * Enrichment paths (both produce the same output schema):
 *   - apiKey provided → CLI calls Haiku directly (fast, no agent needed)
 *   - no apiKey       → LLM fields stay null; use brownfield-enrich skill to
 *                       have the running agent (Claude/Gemini/etc.) enrich them
 *
 * @param {Object} nodes       - dep-graph nodes
 * @param {string} rootDir     - project root
 * @param {string} analysisDir - .wednesday/codebase/analysis/
 * @param {string|null} apiKey - optional; if omitted, enrichment is skipped
 * @returns {Object} comment intel result
 */
async function analyseComments(nodes, rootDir, analysisDir, apiKey = null) {
  // Step 1: collect all comments, grouped by module
  const moduleMap = collectByModule(nodes, rootDir);

  // Step 2: write raw preprocessing report (always, no LLM)
  writeRawReport(moduleMap, analysisDir);

  const allModuleCount = [...moduleMap.values()].filter(m => m.tagged.length + m.untagged.length > 0).length;
  const totalTagged   = [...moduleMap.values()].reduce((n, m) => n + m.tagged.length, 0);
  const totalUntagged = [...moduleMap.values()].reduce((n, m) => n + m.untagged.length, 0);
  console.log(`  [comments] ${moduleMap.size} modules scanned — ${totalTagged} tagged, ${totalUntagged} substantive untagged across ${allModuleCount} modules`);

  // Flatten for summary
  const allTagged = [];
  const allUntagged = [];
  for (const mod of moduleMap.values()) {
    allTagged.push(...mod.tagged);
    allUntagged.push(...mod.untagged);
  }

  // Structural module summaries
  const modules = [...moduleMap.entries()].map(([dir, mod]) => ({
    dir,
    fileCount: mod.files.length,
    files: mod.files,
    taggedCount: mod.tagged.length,
    untaggedCount: mod.untagged.length,
    tagsByType: mod.tagged.reduce((acc, i) => { acc[i.type] = (acc[i.type] || 0) + 1; return acc; }, {}),
    // LLM fields — filled by API key path below, or by brownfield-enrich skill
    purpose: null,
    techDebt: null,
    isBizFeature: null,
    ideas: [],
  }));

  let reversePrd = null;
  let enrichedAt = null;

  if (apiKey) {
    // API key path: enrich directly via Haiku (using nodes for structural context)
    const enriched = await enrichModules(moduleMap, nodes);
    for (const mod of modules) {
      const llm = enriched.get(mod.dir);
      if (llm) {
        mod.purpose      = llm.purpose || null;
        mod.techDebt     = llm.techDebt || null;
        mod.isBizFeature = llm.isBizFeature ?? null;
        mod.ideas        = llm.ideas || [];
      }
    }
    reversePrd = await buildReversePrd(enriched);
    enrichedAt = new Date().toISOString();
    console.log(`  [comments] ✓ LLM enrichment done via API key`);
  } else {
    if (totalTagged + totalUntagged > 0) {
      console.log(`  [comments] No API key — use the brownfield-enrich skill to enrich with purpose, tech debt and ideas`);
    }
  }

  const byType     = allTagged.reduce((acc, i) => { acc[i.type] = (acc[i.type] || 0) + 1; return acc; }, {});
  const bySeverity = allTagged.reduce((acc, i) => { acc[i.severity] = (acc[i.severity] || 0) + 1; return acc; }, {});
  const byFile     = allTagged.reduce((acc, i) => { acc[i.file] = (acc[i.file] || 0) + 1; return acc; }, {});
  const topFiles   = Object.entries(byFile).sort((a, b) => b[1] - a[1]).slice(0, 10).map(([file, count]) => ({ file, count }));

  const result = {
    generatedAt: new Date().toISOString(),
    enrichedAt,   // null = not yet enriched; skill sets this after writing
    reversePrd,
    summary: {
      total: allTagged.length + allUntagged.length,
      taggedTotal: allTagged.length,
      untaggedTotal: allUntagged.length,
      byType,
      bySeverity,
      topFiles,
    },
    modules: modules.sort((a, b) => (b.taggedCount + b.untaggedCount) - (a.taggedCount + a.untaggedCount)),
    items: allTagged.sort((a, b) => {
      const order = { high: 0, medium: 1, low: 2, info: 3 };
      return (order[a.severity] ?? 9) - (order[b.severity] ?? 9);
    }),
  };

  fs.mkdirSync(analysisDir, { recursive: true });
  const outPath = path.join(analysisDir, 'comments.json');
  fs.writeFileSync(outPath, JSON.stringify(result, null, 2));

  return { ...result, outPath };
}

function lineAt(src, idx) {
  return src.slice(0, idx).split('\n').length;
}

module.exports = { analyseComments, extractComments, categorise, collectByModule };
